---
- hosts: all
  become: yes
  user: vagrant
  vars:
    TIMEZONE: UTC
    REDMINE_VERSION: 4.2.1
    RUBY_VERSION: 2.7.3
  tasks:
    - name: Set timezone to {{ TIMEZONE }}
      timezone:
        name: "{{ TIMEZONE }}"

    - name: Selinux set permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Install Needed packages
      yum: state=installed name={{ item }}
      with_items:
        - epel-release.noarch
        - sqlite-devel
        - zlib-devel
        - nodejs
        - wget 
        - unzip 
        - ImageMagick-c++-devel  
        - git

    - name: Install Ruby
      shell: |
        curl -sSL https://rvm.io/mpapis.asc | gpg --import -
        curl -L get.rvm.io | bash -s stable
        source /etc/profile.d/rvm.sh
        rvm reload
        rvm requirements run
        rvm install {{ RUBY_VERSION }}
        rvm use {{ RUBY_VERSION }} --default
        gem install bundle
      args:
        executable: /bin/bash

    - name: Download Redmine    
      shell: |
        mkdir /opt/redmine
        wget http://www.redmine.org/releases/redmine-{{ REDMINE_VERSION }}.zip
        unzip redmine-{{ REDMINE_VERSION }}.zip -d /opt/
        cp -rp /opt/redmine-{{ REDMINE_VERSION }}/* /opt/redmine
      args:
        executable: /bin/bash    

    - name: Copy database.yml
      copy:
        src: ./templates/database.yml
        dest: /opt/redmine/config/database.yml
        force: yes
        group: root
        owner: root
        mode: 0600

    - name: Install Vault plugin
      git:
        repo: 'https://github.com/noshutdown-ru/vault.git'
        dest: /opt/redmine/plugins/vault

    - name: Install TTM plugin
      git:
        repo: 'https://github.com/noshutdown-ru/ttm.git'
        dest: /opt/redmine/plugins/ttm

    - name: Install Redexporter plugin
      git:
        repo: 'https://github.com/noshutdown-ru/redexporter.git'
        dest: /opt/redmine/plugins/redexporter    

    - name: Install Redmine    
      shell: |
        source /root/.bashrc
        cd /opt/redmine
        bundle install
        bundle exec rake generate_secret_token
        RAILS_ENV=production bundle exec rake db:migrate
        RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data
        RAILS_ENV=production bundle exec rake redmine:plugins:migrate
        echo "bundle exec rails server webrick -e production -b 0.0.0.0 -p 80"
      args:
        executable: /bin/bash